# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf860c963336e91b5d73cefe95a4b63570033c2b950e56b85fcd0167ad81a4072dfdffd1c6310383c9030aa87bec1c9c1b1fdfa083b571390c12888eba7582fb

test:
  secret_key_base: e16272819012e57bfe3452a307f3e64441db81a7bcab2aefde1a7fcf8fd50634295df984bc3419cef3963757b88a4af91738d28af2a779ccde8c76c017911ea6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
